name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  build:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        app: [frontend, backend]
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ matrix.node-version }}-
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: |
        if [ -d "${{ matrix.app }}" ]; then
          cd ${{ matrix.app }}
          npm install
        else
          echo "${{ matrix.app }} directory not found"
          exit 1
        fi
    
    - name: Build ${{ matrix.app }} container
      run: |
        if [ -d "${{ matrix.app }}" ]; then
          cd ${{ matrix.app }}
          # Use specific Dockerfile for frontend and backend
          if [ "${{ matrix.app }}" == "frontend" ]; then
            docker build -t hospital-frontend:${{ github.sha }} -f frontend-Dockerfile .
          else
            docker build -t hospital-backend:${{ github.sha }} -f backend-Dockerfile .
          fi
        else
          echo "${{ matrix.app }} directory not found"
          exit 1
        fi
    
    - name: Run ${{ matrix.app }} unit tests
      run: |
        if [ -d "${{ matrix.app }}" ]; then
          docker run --rm hospital-${{ matrix.app }}:${{ github.sha }} npm test -- --json --outputFile=test-results.json
        else
          echo "${{ matrix.app }} directory not found"
          exit 1
        fi
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.app }}-${{ matrix.node-version }}
        path: ${{ matrix.app }}/test-results.json
      if: always()
    
    - name: Run ${{ matrix.app }} linter
      run: |
        if [ -d "${{ matrix.app }}" ]; then
          docker run --rm hospital-${{ matrix.app }}:${{ github.sha }} npm run lint
        else
          echo "${{ matrix.app }} directory not found"
          exit 1
        fi
    
    - name: Run SAST for ${{ matrix.app }}
      uses: github/codeql-action/analyze@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push ${{ matrix.app }} image to DockerHub
      run: |
        if [ -d "${{ matrix.app }}" ]; then
          docker tag hospital-${{ matrix.app }}:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/hospital-${{ matrix.app }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hospital-${{ matrix.app }}:${{ github.sha }}
        else
          echo "${{ matrix.app }} directory not found"
          exit 1
        fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to staging
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to staging environment"
        # Add your deployment script here
