name: CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yaml'

jobs:
  backend:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3
       - name: install dependencies
         run: npm ci
         working-directory: ./backend
         
      # - name: run eslint
       #  run: npx eslint . --ignore-pattern .eslintignore
       #  working-directory: ./backend
       
       - name: build application 
         run: npm run build
         working-directory: ./backend
       - name: unit testing
         run: npm test
         working-directory: ./backend
  frontend:
      runs-on: ubuntu-latest 

      steps:
        - uses: actions/checkout@v3
        - name: install dependencies
          run: npm ci
          working-directory: ./frontend
        - name:  run eslint
          run:   npx eslint . --ignore-pattern .eslintignore
          working-directory: ./frontend
        - name: build frontend
          run: npm run build
          working-directory: ./frontend
        - name: unit testing
          run: npm test 
          working-directory: ./frontend
