name: CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.yaml'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend

      - name: Lint Backend Code
        run: npm run lint
        working-directory: ./backend

      - name: Build application
        run: npm run build
        working-directory: ./backend

      - name: Unit testing
        run: npm test
        working-directory: ./backend

      
      - name: SonarQube Scanner
        env:
          SONAR_HOST_URL: http://34.47.183.81:9000  
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}  
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=backend \
            -Dsonar.sources=./backend \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Build Docker image for backend
        run: docker build -f ./backend/backend-Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend

      - name: Push Docker image to registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Lint Frontend Code
        run: npm run lint || true 
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Unit testing
        run: npm test
        working-directory: ./frontend

      # SonarQube Analysis for Frontend
      - name: SonarQube Scanner
        env:
          SONAR_HOST_URL: http://34.47.183.81:9000  
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}  
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=frontend \
            -Dsonar.sources=./frontend \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Build Docker image for frontend
        run: docker build -f ./frontend/frontend-Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend

      - name: Push Docker image to registry
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
